credentials:
  usernames:
    peytonwates:
      email: Peyton.Wates@GAPAC.com
      name: Peyton Wates
      password: "$$2b$12$UsX/0SgDZ1si613JqlYl9u.3caEbMxtvhshmQMykKSC9whZwVeFnK"
    jaredgordon:
      email: Jared.Gordon@GAPAC.com
      name: Jared Gordon
      password: "$2b$12$uOw/GyGz3bCc6EjHY5JW1ecSYaMeW0.ix0g.w99GNGjl61QRCHgre"
    chriswang:
      email: Christopher.Wang@GAPAC.com
      name: Chris Wang
      password: "$2b$12$4/CZyO4tQeNHW8XhL.NiXegZaCJ44s5ci3/Qu0jh9bCsKNs66fJgW"
    elizabethlim:
      email: Elizabeth.Lim@GAPAC.com
      name: Elizabeth Lim
      password: "$2b$12$oehw4Qz29yqn0inws7lhb.1u9rpEf7UdXttBB3RksPRPiQHf7BXrO"
    miniagong:
      email: Minia.Gong@GAPAC.com
      name: Minia Gong
      password: "$2b$12$Yo86bUbatiGZmukCBfpgXuBv/WmNg2FC1N1Co1i8RCgC/okmCQUKu"
    amberbrown:
      email: Amber.Brown1@GAPAC.com
      name: Amber Brown
      password: "$2b$12$kN6E20GzrVHtlk7TCtSjO.PrE/PcD109U/0cKZsXBjK0xhiL6cXFa"      

cookie:
  name: "some_cookie_name"
  key: "some_signature_key"
  expiry_days: 30

oauth2:
  client_id: "your_client_id"
  client_secret: "your_client_secret"
  redirect_uri: "your_redirect_uri"

