credentials:
  usernames:
    peytonwates:
      email: Peyton.Wates@GAPAC.com
      name: Peyton Wates
      password: "$2b$12$IDvEENKx9xSWNBHb3h38xuEdiJtcK8.JjnzeaoAaZOUgqymmYaeAm"
    jaredgordon:
      email: Jared.Gordon@GAPAC.com
      name: Jared Gordon
      password: "$2b$12$0bqs2iXbfS0GFjjgZkM3v.lrLOn7nkcL1NjNkHhNtuYJIPBTu6uPW"
    chriswang:
      email: Christopher.Wang@GAPAC.com
      name: Chris Wang
      password: "$2b$12$Ar/xLrRqeLXu0q0TyCwrquN0wQbQakZqEZEO0htZdkI0EtboymD7m"


cookie:
  name: "some_cookie_name"
  key: "some_signature_key"
  expiry_days: 30

oauth2:
  client_id: "your_client_id"
  client_secret: "your_client_secret"
  redirect_uri: "your_redirect_uri"

